name: gold_and_use
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.5.6 # Actualiza esta línea a la versión compatible
  html: ^0.15.0  # Agrega esta línea
  image_picker: ^1.0.0
  fl_chart: ^0.63.0
  dio: ^5.4.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geocoding: ^2.1.1


  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  qr_flutter: ^4.1.0
  flutter_lints: ^4.0.0
  # flutter_map: ^5.0.0
  # latlong2: ^0.9.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/splash.gif
    - assets/logo.png 
    - assets/icono_ajustes.png
    - assets/qr_icon.png
    - assets/transacciones.png
    - assets/maps.png
    - assets/Users/icono.png
    - assets/Transacciones/icono.png
    - assets/Empeños/icono.png
    - assets/Inversiones/icono.png
    - assets/Ubicaciones/icono.png
    - assets/Notificaciones/icono.png
